
(() => {
const C=window.COURSE_DATA;
const REPO={owner:'sai-prakash',repo:'Deep-Agent-Folder',branch:'main'};
const allLessons=C.schools.flatMap(s=>s.lessons.map(l=>({...l,schoolId:s.id,schoolTitle:s.title,color:s.color})));
const byId=Object.fromEntries(allLessons.map(l=>[l.id,l]));
const storageKey='ai-engineering-mastery:v1';
const defaultState={schemaVersion:1,completed:[],labs:{},quiz:{},notes:{},settings:{githubUser:'sai-prakash',pace:'5',path:'full'},lastStudy:null,streak:0};
let state=load();
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(storageKey,JSON.stringify(state));updateChrome()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function progress(){return Math.round((state.completed.length/allLessons.length)*100)}
function updateChrome(){const p=progress();$('#progressPct').textContent=p+'%';$('#progressRing').style.setProperty('--p',p);$('#progressLabel').textContent=p===100?'Course mastered':p?'Keep building':'Start here';$('#progressMeta').textContent=`${state.completed.length} of ${allLessons.length} lessons complete`;renderNav()}
function renderNav(){const nav=$('#schoolNav');nav.innerHTML=C.schools.map(s=>{const done=s.lessons.filter(l=>state.completed.includes(l.id)).length;return `<a href="#/school/${s.id}" data-school="${s.id}"><span class="nav-dot" style="--c:${s.color}"></span><span>${esc(s.title)}</span><span class="nav-count">${done}/${s.lessons.length}</span></a>`}).join('')}
function nextLesson(){return allLessons.find(l=>!state.completed.includes(l.id))||allLessons.at(-1)}
function totalMinutes(){return allLessons.reduce((a,l)=>a+l.minutes,0)}
function home(){const next=nextLesson();return `<div class="hero"><div><div class="eyebrow">Learn by building · GitHub-native progress</div><h1>${esc(C.title)}</h1><p class="lead">${esc(C.tagline)} Learn LLM foundations, grounding, agents, eval-driven development, production operations and ML by repeatedly building, breaking, measuring and improving real systems.</p><div class="loop">${C.loop.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="hero-panel"><div class="stat-grid"><div class="stat"><strong>${allLessons.length}</strong><span>hands-on lessons</span></div><div class="stat"><strong>${C.projects.length}</strong><span>portfolio systems</span></div><div class="stat"><strong>${Math.round(totalMinutes()/60)}h</strong><span>core guided work</span></div><div class="stat"><strong>${progress()}%</strong><span>your progress</span></div></div><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><small class="eyebrow">Next best action</small><h3 style="margin-top:7px">${esc(next.title)}</h3><p style="color:var(--muted)">${esc(next.concept.slice(0,130))}…</p><a class="primary" style="display:inline-block;text-decoration:none" href="#/lesson/${next.id}">Continue learning →</a></div></div>
<div class="section-head"><div><div class="eyebrow">Curriculum</div><h2>Eight schools. One engineering loop.</h2></div><p>Each lesson has six modes: understand the concept, predict behavior, build it, break it, measure it, then pass a mastery gate.</p></div>
<div class="school-grid">${C.schools.map(s=>schoolCard(s)).join('')}</div>
<div class="section-head"><div><div class="eyebrow">Mastery model</div><h2>Progress means demonstrated capability.</h2></div></div><div class="mastery-strip">${C.masteryLevels.map((x,i)=>`<div><small>Level ${i+1}</small><strong>${esc(x)}</strong></div>`).join('')}</div>
<div class="github-box"><div><strong>GitHub is the durable learning record.</strong><div style="color:var(--muted);margin-top:4px">Local progress is instant. Checkpoints are stored in the repository through validated GitHub Issues + Actions—no browser token and no separate backend.</div></div><button class="secondary" onclick="window.CourseApp.checkpoint()">Create checkpoint ↗</button></div>`}
function schoolCard(s){const done=s.lessons.filter(l=>state.completed.includes(l.id)).length;return `<a class="school-card" style="--c:${s.color}" href="#/school/${s.id}"><small>${s.subtitle}</small><h3>${esc(s.title)}</h3><p>${s.lessons.length} lessons · ${s.lessons.reduce((a,l)=>a+l.minutes,0)} guided minutes</p><div class="school-footer"><span class="pill">${done===s.lessons.length?'Mastered':done?`${done} complete`:'Not started'}</span><span class="school-progress">Project: ${esc(s.project)}</span></div></a>`}
function schoolView(id){const s=C.schools.find(x=>x.id===id);if(!s)return notFound();const p=C.projects.find(x=>x.after===id);return `<div class="lesson-title"><div class="eyebrow">School ${esc(s.id.slice(1))}</div><h1>${esc(s.title.replace(/^\d+ · /,''))}</h1><p class="lead">${esc(s.subtitle)}</p></div><div class="roadmap">${s.lessons.map((l,i)=>{const done=state.completed.includes(l.id);return `<a class="lesson-row ${done?'done':''}" href="#/lesson/${l.id}"><span class="lesson-num">${done?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${esc(l.title)}</strong><small>${esc(l.concept.slice(0,120))}…</small></span><span class="lesson-meta">${l.minutes} min<br>${done?'mastered':'learn →'}</span></a>`}).join('')}</div>${p?projectCard(p):''}`}
function projectCard(p){return `<section class="project-card"><span class="pill">Portfolio build</span><h2 style="margin-top:12px">${esc(p.title)}</h2><p>${esc(p.brief)}</p><h3>Required evidence</h3><ul>${p.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function lessonView(id,tab='learn'){const l=byId[id];if(!l)return notFound();const idx=allLessons.findIndex(x=>x.id===id);const checks=state.labs[id]||{};const tabs=['learn','predict','build','break','measure','master'];let body='';
 if(tab==='learn')body=`<p class="big-copy">${esc(l.concept)}</p><div class="mental"><strong>Mental model</strong>${esc(l.mentalModel)}</div><div class="callout"><strong>Why this matters</strong><p>AI components are probabilistic. This lesson is complete only when you can connect the concept to a concrete failure mode and an engineering control.</p></div>`;
 if(tab==='predict')body=`<div class="task-box"><h3>01 · Predict before touching code</h3><p>${esc(l.predict)}</p></div>${scratch(id,'predict')}`;
 if(tab==='build')body=`<div class="task-box"><h3>02 · Build</h3><p>${esc(l.build)}</p></div>${scratch(id,'build')}`;
 if(tab==='break')body=`<div class="task-box"><h3>03 · Break it on purpose</h3><p>${esc(l.breakIt)}</p></div><p>The goal is not chaos. Create the smallest reproducible failure, capture the trace/input/output, and classify the failure before changing anything.</p>${scratch(id,'break')}`;
 if(tab==='measure')body=`<div class="task-box"><h3>04 · Measure</h3><p>${esc(l.measure)}</p></div><div class="measure-list"><div>Record a baseline before the change.</div><div>Change one primary variable at a time.</div><div>Keep examples that regress; they become future evaluation cases.</div><div>Report uncertainty when the dataset is too small to support a confident conclusion.</div></div><div class="callout"><strong>Improve</strong><p>${esc(l.improve)}</p></div>${scratch(id,'measure')}`;
 if(tab==='master')body=master(id,l);
 return `<div class="lesson-title" style="--school:${l.color}"><div class="eyebrow">${esc(l.schoolTitle)} · ${l.minutes} min</div><h1>${esc(l.title)}</h1><p class="lead">Mastery is earned by an experiment you can explain, not by reading this page.</p></div><div class="lesson-layout"><div><div class="lesson-tabs">${tabs.map(t=>`<button class="${t===tab?'active':''}" onclick="window.CourseApp.tab('${id}','${t}')">${({learn:'Understand',predict:'Predict',build:'Build',break:'Break it',measure:'Measure',master:'Master'})[t]}</button>`).join('')}</div><article class="lesson-panel" style="--school:${l.color}">${body}<div class="next-prev">${idx>0?`<a class="secondary" href="#/lesson/${allLessons[idx-1].id}">← Previous</a>`:'<span></span>'}${idx<allLessons.length-1?`<a class="primary" href="#/lesson/${allLessons[idx+1].id}">Next lesson →</a>`:'<a class="primary" href="#/">Course dashboard →</a>'}</div></article></div><aside class="lesson-aside"><div class="aside-card"><small>Lesson progress</small><strong>${state.completed.includes(id)?'Mastered ✓':'In progress'}</strong><div class="checklist">${['predict','build','break','measure'].map(k=>`<label><input type="checkbox" ${checks[k]?'checked':''} onchange="window.CourseApp.labCheck('${id}','${k}',this.checked)"> ${({predict:'Prediction recorded',build:'Build completed',break:'Failure reproduced',measure:'Metrics recorded'})[k]}</label>`).join('')}</div></div><div class="aside-card"><small>Mastery standard</small><strong>${esc(l.mastery)}</strong></div><div class="aside-card"><small>GitHub evidence</small><p style="font-size:13px">Commit lab work, traces and eval results to your fork/project. Use a checkpoint to persist course progress.</p><button class="secondary wide" onclick="window.CourseApp.checkpoint('${id}')">Checkpoint ↗</button></div></aside></div>`}
function scratch(id,kind){const v=(state.notes[id]||{})[kind]||'';return `<label><strong>Lab notebook</strong><textarea class="scratch" placeholder="Hypothesis → evidence → result → next move" oninput="window.CourseApp.note('${id}','${kind}',this.value)">${esc(v)}</textarea></label>`}
function master(id,l){const q=state.quiz[id];const checks=state.labs[id]||{};const labsDone=['predict','build','break','measure'].every(k=>checks[k]);return `<div class="task-box"><h3>Mastery gate</h3><p>${esc(l.mastery)}</p></div><div class="callout"><strong>Explain it back</strong><p>${esc(l.explain)}</p></div><h3>${esc(l.quiz.question)}</h3>${l.quiz.choices.map((c,i)=>`<button class="quiz-choice ${q?.selected===i?(i===l.quiz.answer?'correct':'wrong'):''}" onclick="window.CourseApp.quiz('${id}',${i})">${String.fromCharCode(65+i)}. ${esc(c)}</button>`).join('')}${q?`<div class="feedback"><strong>${q.correct?'Correct':'Not yet'}</strong><br>${esc(l.quiz.explanation)}</div>`:''}<hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><div class="callout"><strong>Completion rule</strong><p>Prediction + build + break + measure must be checked, and the mastery question must be correct.</p><button class="primary" ${!(labsDone&&q?.correct)?'disabled style="opacity:.45;cursor:not-allowed"':''} onclick="window.CourseApp.complete('${id}')">${state.completed.includes(id)?'Mastered ✓':'Mark lesson mastered'}</button></div>`}
function notFound(){return `<div class="empty"><h2>Nothing here.</h2><a href="#/">Return to course</a></div>`}
function router(){const bits=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);let html;if(!bits.length)html=home();else if(bits[0]==='school')html=schoolView(bits[1]);else if(bits[0]==='lesson')html=lessonView(bits[1],bits[2]||'learn');else html=notFound();$('#view').innerHTML=html;$('#crumb').textContent=bits[0]==='lesson'?(byId[bits[1]]?.title||C.title):bits[0]==='school'?(C.schools.find(s=>s.id===bits[1])?.title||C.title):C.title;document.querySelectorAll('#schoolNav a').forEach(a=>a.classList.toggle('active',a.dataset.school===(bits[0]==='school'?bits[1]:byId[bits[1]]?.schoolId)));window.scrollTo(0,0);updateChrome()}
function checkpoint(focus){const user=state.settings.githubUser||'';if(!user){$('#settingsDialog').showModal();toast('Add your GitHub username first');return}const compact={schemaVersion:1,user,completed:state.completed,quiz:Object.fromEntries(Object.entries(state.quiz).filter(([,v])=>v?.correct).map(([k,v])=>[k,{correct:true}])),streak:state.streak,timestamp:new Date().toISOString(),focus:focus||null};const body=`AI Engineering Mastery progress checkpoint for @${user}.\n\n<!-- PROGRESS_JSON_START -->\n\`\`\`json\n${JSON.stringify(compact)}\n\`\`\`\n<!-- PROGRESS_JSON_END -->\n\nThis issue is machine-processed by the progress sync workflow and will be closed automatically.`;const url=`https://github.com/${REPO.owner}/${REPO.repo}/issues/new?title=${encodeURIComponent('[Progress Sync] @'+user)}&body=${encodeURIComponent(body)}`;window.open(url,'_blank','noopener,noreferrer')}
async function restoreGithub(){const user=$('#githubUser').value.trim();if(!user)return toast('Enter a GitHub username');try{const url=`https://api.github.com/repos/${REPO.owner}/${REPO.repo}/contents/progress/${encodeURIComponent(user)}.json?ref=${REPO.branch}&t=${Date.now()}`;const r=await fetch(url,{headers:{Accept:'application/vnd.github.raw+json'}});if(!r.ok)throw new Error('No checkpoint found');const d=await r.json();state.completed=Array.isArray(d.completed)?d.completed.filter(x=>byId[x]):state.completed;state.quiz={...state.quiz,...(d.quiz||{})};state.settings.githubUser=user;save();router();$('#settingsDialog').close();toast('Restored GitHub checkpoint')}catch(e){toast(e.message||'Could not restore checkpoint')}}
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai-engineering-progress.json';a.click();URL.revokeObjectURL(a.href)}
function setupSearch(){const dlg=$('#searchDialog'),input=$('#searchInput');function run(){const q=input.value.toLowerCase().trim();const rows=q?allLessons.filter(l=>[l.title,l.concept,l.build,l.measure].join(' ').toLowerCase().includes(q)).slice(0,24):allLessons.slice(0,12);$('#searchResults').innerHTML=rows.map(l=>`<a class="search-item" href="#/lesson/${l.id}" onclick="document.querySelector('#searchDialog').close()"><strong>${esc(l.title)}</strong><br><small>${esc(l.schoolTitle)} · ${l.minutes} min</small></a>`).join('')}input.addEventListener('input',run);run();$('#searchBtn').onclick=()=>{dlg.showModal();setTimeout(()=>input.focus(),20)};document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();dlg.showModal();setTimeout(()=>input.focus(),20)}})}
window.CourseApp={tab:(id,t)=>{location.hash=`/lesson/${id}/${t}`},note:(id,k,v)=>{state.notes[id]={...(state.notes[id]||{}),[k]:v};save()},labCheck:(id,k,v)=>{state.labs[id]={...(state.labs[id]||{}),[k]:v};save()},quiz:(id,i)=>{const l=byId[id];state.quiz[id]={selected:i,correct:i===l.quiz.answer};save();router()},complete:id=>{const q=state.quiz[id],labs=state.labs[id]||{};if(!(q?.correct&&['predict','build','break','measure'].every(k=>labs[k])))return toast('Finish the lab evidence and mastery question first');if(!state.completed.includes(id))state.completed.push(id);const today=new Date().toISOString().slice(0,10);if(state.lastStudy!==today){const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastStudy===prev?(state.streak||0)+1:1;state.lastStudy=today}save();router();toast('Lesson mastered — evidence beats vibes.')},checkpoint,restoreGithub};
$('#githubSyncBtn').onclick=()=>checkpoint();$('#profileBtn').onclick=$('#settingsBtn').onclick=()=>{$('#githubUser').value=state.settings.githubUser||'';$('#pace').value=state.settings.pace||'5';$('#path').value=state.settings.path||'full';$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=()=>{state.settings={githubUser:$('#githubUser').value.trim(),pace:$('#pace').value,path:$('#path').value};save();$('#settingsDialog').close();toast('Settings saved')};$('#loadGithubBtn').onclick=restoreGithub;$('#exportBtn').onclick=exportState;$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);state={...defaultState,...d};save();router();toast('Progress imported')}catch{toast('Invalid progress file')}};r.readAsText(f)};$('#mobileNav').onclick=()=>$('.sidebar').classList.toggle('open');document.addEventListener('click',e=>{if(e.target.closest('.sidebar a')&&innerWidth<961)$('.sidebar').classList.remove('open')});window.addEventListener('hashchange',router);setupSearch();updateChrome();router();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
