(() => {
const raw=window.COURSE_RAW||[];
function makeLesson(x,school){const [id,title,concept,build,breakIt,measure]=x;const project=/Project|Capstone/.test(title);return {id,title,minutes:project?150:55,concept,build,breakIt,measure,school:school.title,mentalModel:`For ${title.toLowerCase()}, ask four things: what is uncertain, what remains deterministic, what evidence can reveal failure, and what boundary limits the blast radius? Keep the uncertain component small enough to observe.`,predict:`Before building, write one concrete prediction about how a naive implementation of ${title} will fail on a realistic edge case. State what evidence would prove you wrong.`,improve:`Choose exactly one change based on the largest measured failure category. Re-run the same cases. Keep the change only if evidence improves the target metric without an unacceptable regression elsewhere.`,explain:`Explain ${title} to another engineer in five sentences: purpose, architecture, one failure mode, the metric you trust, and when you would choose a simpler alternative.`,mastery:'Show a prediction, a working artifact or trace, one reproduced failure, before/after measurement, and a short explanation of why the change worked. Reading alone does not count.',quiz:{question:`What is the strongest evidence that you understand ${title}?`,choices:['You can define the term from memory','A demo works once','You can predict a failure, reproduce it, measure it and improve the system','You used the newest framework'],answer:2,explanation:'AI engineering mastery is demonstrated by repeatable behavior under measurement, including failure analysis—not vocabulary or a one-off demo.'}}}
const projectDefs=[['Model Lab','S1','Benchmark models/configs by quality, tokens, latency and cost.'],['Evidence Engine','S2','Ground answers in documents plus structured data with citations and retrieval evals.'],['Research Operator','S3','Build a tool-using agent with state, recovery, approvals and traces.'],['Eval Factory','S4','Build deterministic + semantic grading, meta-evals, slices and regression reports.'],['Production AI Service','S5','Operate a secure, observable, cost-aware service with release gates.'],['Hybrid ML + LLM System','S6','Combine classical prediction, LLM reasoning, retrieval and tools intentionally.'],['Production AI Analyst','S7','Ship the end-to-end capstone with 200+ evals and optimization evidence.']];
const projects=projectDefs.map(([title,after,brief])=>({title,after,brief,deliverables:['Architecture and README','Reproducible implementation','Failure cases and traces','Before/after evaluation evidence','Next experiment or production decision']}));
const projectBySchool=Object.fromEntries(projects.map(p=>[p.after,p.title]));
const schools=raw.map(s=>({...s,subtitle:s.description,project:projectBySchool[s.id]||'Foundation build',lessons:s.lessons.map(x=>makeLesson(x,s))}));
const meta={title:'AI Engineering Mastery',subtitle:'Build reliable systems from unreliable AI components',version:'2026.08',lessonCount:schools.reduce((n,s)=>n+s.lessons.length,0),philosophy:'Understand → Predict → Build → Break → Measure → Improve → Explain',sourceNote:"Inspired by Andrew Ng's AI Engineering Skills Map and expanded into an independent learn-by-building program."};
window.COURSE_DATA={...meta,tagline:meta.subtitle,loop:['Understand','Predict','Build','Break','Measure','Improve','Explain'],masteryLevels:['AI Literate','AI Builder','AI Engineer','AI Systems Engineer'],meta,schools,projects,graduation:{levels:['AI Literate','AI Builder','AI Engineer','AI Systems Engineer']}};
})();
